[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

[features]
performance = ["evmrs/performance"]
mimalloc = ["evmrs/mimalloc"]
stack-array = ["evmrs/stack-array"]
custom-evmc = ["evmrs/custom-evmc"]
jumptable = ["evmrs/jumptable"]
hash-cache = ["evmrs/hash-cache"]
jump-cache = ["evmrs/jump-cache"]
thread-local-cache = ["evmrs/thread-local-cache"]
jumptable-tail-call = ["evmrs/jumptable-tail-call"]

[dependencies]
evmrs = { path = ".." }
driver = { path = "../driver" }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "interpreter"
harness = false
