[package]
name = "evmrs"
version = "0.1.0"
edition = "2021"

[dependencies]
bnum = "0.11.0"
evmc-vm = { git = "https://github.com/LorenzSchueler/evmc", branch = "tosca-extensions" } # TODO use Fantom-foundation/evmc once merged

[lib]
crate-type = ["cdylib"]
