[package]
name = "evmrs"
version = "0.1.0"
edition = "2021"

[dependencies]
bnum = "0.11.0"
evmc-declare = { path = "../../evmc/bindings/rust/evmc-declare" }
evmc-vm = { path = "../../evmc/bindings/rust/evmc-vm" }

[lib]
crate-type = ["cdylib"]
