// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source processor.go -destination processor_mock.go -package vm
//

// Package vm is a generated GoMock package.
package vm

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProcessor is a mock of Processor interface.
type MockProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockProcessorMockRecorder
}

// MockProcessorMockRecorder is the mock recorder for MockProcessor.
type MockProcessorMockRecorder struct {
	mock *MockProcessor
}

// NewMockProcessor creates a new mock instance.
func NewMockProcessor(ctrl *gomock.Controller) *MockProcessor {
	mock := &MockProcessor{ctrl: ctrl}
	mock.recorder = &MockProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessor) EXPECT() *MockProcessorMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockProcessor) Run(arg0 Revision, arg1 Transaction, arg2 TransactionContext, arg3 TxContext) (Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockProcessorMockRecorder) Run(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockProcessor)(nil).Run), arg0, arg1, arg2, arg3)
}

// MockTxContext is a mock of TxContext interface.
type MockTxContext struct {
	ctrl     *gomock.Controller
	recorder *MockTxContextMockRecorder
}

// MockTxContextMockRecorder is the mock recorder for MockTxContext.
type MockTxContextMockRecorder struct {
	mock *MockTxContext
}

// NewMockTxContext creates a new mock instance.
func NewMockTxContext(ctrl *gomock.Controller) *MockTxContext {
	mock := &MockTxContext{ctrl: ctrl}
	mock.recorder = &MockTxContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxContext) EXPECT() *MockTxContextMockRecorder {
	return m.recorder
}

// AccessAccount mocks base method.
func (m *MockTxContext) AccessAccount(addr Address) AccessStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessAccount", addr)
	ret0, _ := ret[0].(AccessStatus)
	return ret0
}

// AccessAccount indicates an expected call of AccessAccount.
func (mr *MockTxContextMockRecorder) AccessAccount(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessAccount", reflect.TypeOf((*MockTxContext)(nil).AccessAccount), addr)
}

// AccessStorage mocks base method.
func (m *MockTxContext) AccessStorage(addr Address, key Key) AccessStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessStorage", addr, key)
	ret0, _ := ret[0].(AccessStatus)
	return ret0
}

// AccessStorage indicates an expected call of AccessStorage.
func (mr *MockTxContextMockRecorder) AccessStorage(addr, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessStorage", reflect.TypeOf((*MockTxContext)(nil).AccessStorage), addr, key)
}

// AccountExists mocks base method.
func (m *MockTxContext) AccountExists(addr Address) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountExists", addr)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AccountExists indicates an expected call of AccountExists.
func (mr *MockTxContextMockRecorder) AccountExists(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountExists", reflect.TypeOf((*MockTxContext)(nil).AccountExists), addr)
}

// Call mocks base method.
func (m *MockTxContext) Call(kind CallKind, parameter CallParameter) (CallResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", kind, parameter)
	ret0, _ := ret[0].(CallResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Call indicates an expected call of Call.
func (mr *MockTxContextMockRecorder) Call(kind, parameter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockTxContext)(nil).Call), kind, parameter)
}

// CreateSnapshot mocks base method.
func (m *MockTxContext) CreateSnapshot() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot")
	ret0, _ := ret[0].(int)
	return ret0
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockTxContextMockRecorder) CreateSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockTxContext)(nil).CreateSnapshot))
}

// EmitLog mocks base method.
func (m *MockTxContext) EmitLog(addr Address, topics []Hash, data []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EmitLog", addr, topics, data)
}

// EmitLog indicates an expected call of EmitLog.
func (mr *MockTxContextMockRecorder) EmitLog(addr, topics, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitLog", reflect.TypeOf((*MockTxContext)(nil).EmitLog), addr, topics, data)
}

// GetBalance mocks base method.
func (m *MockTxContext) GetBalance(addr Address) Value {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", addr)
	ret0, _ := ret[0].(Value)
	return ret0
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockTxContextMockRecorder) GetBalance(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockTxContext)(nil).GetBalance), addr)
}

// GetBlockHash mocks base method.
func (m *MockTxContext) GetBlockHash(number int64) Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockHash", number)
	ret0, _ := ret[0].(Hash)
	return ret0
}

// GetBlockHash indicates an expected call of GetBlockHash.
func (mr *MockTxContextMockRecorder) GetBlockHash(number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockHash", reflect.TypeOf((*MockTxContext)(nil).GetBlockHash), number)
}

// GetCode mocks base method.
func (m *MockTxContext) GetCode(addr Address) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCode", addr)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetCode indicates an expected call of GetCode.
func (mr *MockTxContextMockRecorder) GetCode(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCode", reflect.TypeOf((*MockTxContext)(nil).GetCode), addr)
}

// GetCodeHash mocks base method.
func (m *MockTxContext) GetCodeHash(addr Address) Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCodeHash", addr)
	ret0, _ := ret[0].(Hash)
	return ret0
}

// GetCodeHash indicates an expected call of GetCodeHash.
func (mr *MockTxContextMockRecorder) GetCodeHash(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodeHash", reflect.TypeOf((*MockTxContext)(nil).GetCodeHash), addr)
}

// GetCodeSize mocks base method.
func (m *MockTxContext) GetCodeSize(addr Address) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCodeSize", addr)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetCodeSize indicates an expected call of GetCodeSize.
func (mr *MockTxContextMockRecorder) GetCodeSize(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodeSize", reflect.TypeOf((*MockTxContext)(nil).GetCodeSize), addr)
}

// GetCommittedStorage mocks base method.
func (m *MockTxContext) GetCommittedStorage(addr Address, key Key) Word {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommittedStorage", addr, key)
	ret0, _ := ret[0].(Word)
	return ret0
}

// GetCommittedStorage indicates an expected call of GetCommittedStorage.
func (mr *MockTxContextMockRecorder) GetCommittedStorage(addr, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommittedStorage", reflect.TypeOf((*MockTxContext)(nil).GetCommittedStorage), addr, key)
}

// GetNonce mocks base method.
func (m *MockTxContext) GetNonce(arg0 Address) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNonce", arg0)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetNonce indicates an expected call of GetNonce.
func (mr *MockTxContextMockRecorder) GetNonce(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNonce", reflect.TypeOf((*MockTxContext)(nil).GetNonce), arg0)
}

// GetStorage mocks base method.
func (m *MockTxContext) GetStorage(addr Address, key Key) Word {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorage", addr, key)
	ret0, _ := ret[0].(Word)
	return ret0
}

// GetStorage indicates an expected call of GetStorage.
func (mr *MockTxContextMockRecorder) GetStorage(addr, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorage", reflect.TypeOf((*MockTxContext)(nil).GetStorage), addr, key)
}

// GetTransactionContext mocks base method.
func (m *MockTxContext) GetTransactionContext() TransactionContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionContext")
	ret0, _ := ret[0].(TransactionContext)
	return ret0
}

// GetTransactionContext indicates an expected call of GetTransactionContext.
func (mr *MockTxContextMockRecorder) GetTransactionContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionContext", reflect.TypeOf((*MockTxContext)(nil).GetTransactionContext))
}

// HasSelfDestructed mocks base method.
func (m *MockTxContext) HasSelfDestructed(addr Address) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasSelfDestructed", addr)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasSelfDestructed indicates an expected call of HasSelfDestructed.
func (mr *MockTxContextMockRecorder) HasSelfDestructed(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasSelfDestructed", reflect.TypeOf((*MockTxContext)(nil).HasSelfDestructed), addr)
}

// IsAddressInAccessList mocks base method.
func (m *MockTxContext) IsAddressInAccessList(addr Address) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAddressInAccessList", addr)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAddressInAccessList indicates an expected call of IsAddressInAccessList.
func (mr *MockTxContextMockRecorder) IsAddressInAccessList(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAddressInAccessList", reflect.TypeOf((*MockTxContext)(nil).IsAddressInAccessList), addr)
}

// IsSlotInAccessList mocks base method.
func (m *MockTxContext) IsSlotInAccessList(addr Address, key Key) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSlotInAccessList", addr, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// IsSlotInAccessList indicates an expected call of IsSlotInAccessList.
func (mr *MockTxContextMockRecorder) IsSlotInAccessList(addr, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSlotInAccessList", reflect.TypeOf((*MockTxContext)(nil).IsSlotInAccessList), addr, key)
}

// RestoreSnapshot mocks base method.
func (m *MockTxContext) RestoreSnapshot(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RestoreSnapshot", arg0)
}

// RestoreSnapshot indicates an expected call of RestoreSnapshot.
func (mr *MockTxContextMockRecorder) RestoreSnapshot(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreSnapshot", reflect.TypeOf((*MockTxContext)(nil).RestoreSnapshot), arg0)
}

// SelfDestruct mocks base method.
func (m *MockTxContext) SelfDestruct(addr, beneficiary Address) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelfDestruct", addr, beneficiary)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SelfDestruct indicates an expected call of SelfDestruct.
func (mr *MockTxContextMockRecorder) SelfDestruct(addr, beneficiary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelfDestruct", reflect.TypeOf((*MockTxContext)(nil).SelfDestruct), addr, beneficiary)
}

// SetBalance mocks base method.
func (m *MockTxContext) SetBalance(arg0 Address, arg1 Value) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBalance", arg0, arg1)
}

// SetBalance indicates an expected call of SetBalance.
func (mr *MockTxContextMockRecorder) SetBalance(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBalance", reflect.TypeOf((*MockTxContext)(nil).SetBalance), arg0, arg1)
}

// SetCode mocks base method.
func (m *MockTxContext) SetCode(arg0 Address, arg1 []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCode", arg0, arg1)
}

// SetCode indicates an expected call of SetCode.
func (mr *MockTxContextMockRecorder) SetCode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCode", reflect.TypeOf((*MockTxContext)(nil).SetCode), arg0, arg1)
}

// SetNonce mocks base method.
func (m *MockTxContext) SetNonce(arg0 Address, arg1 uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetNonce", arg0, arg1)
}

// SetNonce indicates an expected call of SetNonce.
func (mr *MockTxContextMockRecorder) SetNonce(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNonce", reflect.TypeOf((*MockTxContext)(nil).SetNonce), arg0, arg1)
}

// SetStorage mocks base method.
func (m *MockTxContext) SetStorage(addr Address, key Key, value Word) StorageStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStorage", addr, key, value)
	ret0, _ := ret[0].(StorageStatus)
	return ret0
}

// SetStorage indicates an expected call of SetStorage.
func (mr *MockTxContextMockRecorder) SetStorage(addr, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStorage", reflect.TypeOf((*MockTxContext)(nil).SetStorage), addr, key, value)
}
