name: cpp-OSX

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-osx.yml'
      - 'cpp/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-osx.yml'
      - 'cpp/**'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run C++ tests
      run: make test-cpp
