name: cpp-tests
on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-tests.yml'
      - 'cpp/**'
      - Makefile
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-tests.yml'
      - 'cpp/**'
      - Makefile
jobs:
  tests-check:
    name: Tests Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: egor-tensin/setup-clang@v1
        with:
          version: latest

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.27.x'

      - name: Run C++ tests
        run: make test-cpp-asan