name: cpp-OSX

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-osx.yml'
      - 'cpp/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-osx.yml'
      - 'cpp/**'

env:
  BAZEL_USE_CPP_ONLY_TOOLCHAIN: 1

jobs:

  build:
    runs-on: macos-latest
    env:
      TEST_TMPDIR: "/Users/runner/.cache/bazel"
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
       path: "/Users/runner/.cache/bazel"
       key: bazel-cpp-osx

    - name: Run C++ tests
      working-directory: ./cpp
      run: |
        export PATH="$(brew --prefix)/opt/llvm/bin:$PATH" 
        bazel test --verbose_failures --test_output=errors --action_env CC=$(brew --prefix llvm@15)/bin/clang --linkopt=-fuse-ld=lld //...
