# Copyright (c) 2024 Fantom Foundation
#
# Use of this software is governed by the Business Source License included
# in the LICENSE file and at fantom.foundation/bsl11.
#
# Change Date: 2028-4-16
#
# On the date above, in accordance with the Business Source License, use of
# this software will be governed by the GNU Lesser General Public License v3.

name: cpp-linter
on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-linter.yml'
      - 'cpp/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-linter.yml'
      - 'cpp/**'
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check.
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: '14'
          check-path: 'cpp'
          run: find cpp/ -iname *.h -o -iname *.cc | xargs clang-format --dry-run -Werror
