name: cpp-tests

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-tests.yml'
      - 'cpp/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-tests.yml'
      - 'cpp/**'

jobs:
  tests-check:
    name: Tests Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: egor-tensin/setup-clang@v1

      - name: Build C++
        run: make tosca-cpp-asan

      - name: Run C++ tests
        run: make test-cpp
