name: cpp-tests

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-tests.yml'
      - 'cpp/**'
      - Makefile
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-tests.yml'
      - 'cpp/**'
      - Makefile

jobs:
  tests-check:
    name: Tests Check
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run C++ tests
        run: make test-cpp-asan
