# Copyright (c) 2024 Fantom Foundation
#
# Use of this software is governed by the Business Source License included
# in the LICENSE file and at fantom.foundation/bsl11.
#
# Change Date: 2028-4-16
#
# On the date above, in accordance with the Business Source License, use of
# this software will be governed by the GNU Lesser General Public License v3.

name: golangci-lint
on:
  push:
    branches: [ "main" ]
    paths:
      - 'go/**'
      - 'go.mod'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'go/**'
      - 'go.mod'

jobs:
  ci:
    name: "lint"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive
    - uses: dominikh/staticcheck-action@v1
      with:
        version: "latest"