# Copyright (c) 2024 Fantom Foundation
#
# Use of this software is governed by the Business Source License included
# in the LICENSE file and at fantom.foundation/bsl11.
#
# Change Date: 2028-4-16
#
# On the date above, in accordance with the Business Source License, use of
# this software will be governed by the GNU Lesser General Public License v3.

name: lint-go

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go.yml'
      - 'go/**'
      - Makefile
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go.yml'
      - 'go/**'
      - Makefile

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.27.x'

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21
        cache: false

    - name: Lint code
      run: make lint-go
