name: Go-OSX

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go-osx.yml'
      - 'cpp/**'
      - 'go/**'
      - Makefile
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go-osx.yml'
      - 'cpp/**'
      - 'go/**'
      - Makefile

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21
        cache: false

    - name: Build Go
      run: make tosca-go

    - name: Run Go tests
      run: make test-go

    - name: CT rule coverage test
      run: go run ./go/ct/driver test

    #- name: CT on LFVM
    #  run: go run ./go/ct/driver run lfvm
